[package]
name = "rapier2d-wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rapier2d_wrapper"
#crate-type = ["cdylib"]	# Creates dynamic lib
crate-type = ["staticlib"]	# Creates static lib

[dependencies]
rapier2d = { version = "0.14.0", features = [ "simd-stable"] } 
lazy_static = "1.4.0"
